content:
  - name: my-pages
    label: "Website Pages"
    type: collection
    path: "**.html"
    format: html
    fields:
      - name: body
        label: "Edit Page Content"
        type: rich-text
