source: .

paths:
  uploads: assets
  static: assets

collections_config:
  pages:
    path: .
    glob:
      - "*.html"
      - "**/*.html"
    output: true
    _enabled_editors:
      - visual
      - content
