backend:
  name: github
  repo: ArenAthletic/ARENATHLETIC
  branch: main

media_folder: "export-static/images"
public_folder: "/images"

collections:
  - name: home
    label: Home
    files:
      - file: content/home.json
        label: Home Page
        name: home
        fields:
          - { label: Hero Title, name: hero_title, widget: string }
          - { label: Hero Subtitle, name: hero_subtitle, widget: string }
